# Generated by Django 4.2.4 on 2023-08-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='count',
            new_name='amount',
        ),
    ]
