# Generated by Django 4.2.4 on 2023-08-24 22:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientrecipe_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет'),
        ),
    ]
