# Generated by Django 4.2.4 on 2023-08-24 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть ниже 1'), django.core.validators.MaxValueValidator(2000, message='Количество не может превышать 2000')], verbose_name='Количество'),
        ),
    ]
