# Generated by Django 4.2.4 on 2023-08-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_subscribe_unique_subscribe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('id',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписка'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователь'},
        ),
    ]
